#!/bin/bash

set -euo pipefail

# Initialization - load function handler
source ./"$(echo $_HANDLER | cut -d. -f1).sh"

# Info custom runtime ready
curl -d " " -X POST -s "http://$SCF_RUNTIME_API:$SCF_RUNTIME_API_PORT/runtime/init/ready"

# Processing
while true
do
  HEADERS="$(mktemp)"
  # Get an event. The HTTP request will block until one is received
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET -s "http://$SCF_RUNTIME_API:$SCF_RUNTIME_API_PORT/runtime/invocation/next")
  
  export HOME=/tmp/
  export PATH=$PATH:${USER_CODE_ROOT}/bin
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${USER_CODE_ROOT}/lib

  ./graph_api_app.sh
  RESPONSE="{\"status\": 200, \"date\": $(date)}"
  
  # Send the response
  curl -X POST -s "http://$SCF_RUNTIME_API:$SCF_RUNTIME_API_PORT/runtime/invocation/response"  -d "$RESPONSE"
done
